#!/bin/bash

mkdir img/rata_tmp
pushd img/rata_tmp

gimp --no-data --no-fonts --no-interface -b "(sg-save-layer-cmd \"../../res/rata-3.xcf\" \"*\")" -b "(gimp-quit 0)"

montage -geometry +0+0 -background none \
arm-0.png \
arm-23.png \
arm-45.png \
arm-68.png \
arm-90.png \
arm-113.png \
arm-135.png \
arm-158.png \
arm-180.png \
-depth 8 ../rata-arm\;32x32\,15\,16.png

montage -geometry +0+0 -background none \
forearm-0.png \
forearm-23.png \
forearm-45.png \
forearm-68.png \
forearm-90.png \
forearm-113.png \
forearm-135.png \
forearm-158.png \
forearm-180.png \
-depth 8 ../rata-forearm\;32x32\,15\,19.png

montage -geometry +0+0 -background none \
body-stand.png \
body-walk.png \
body-tiptoe.png \
body-kneel.png \
body-crawl.png \
body-crawl2.png \
body-sit.png \
body-hurtbk.png \
body-laybk.png \
body-hurtfd.png \
body-layfd.png \
body-grab.png \
-depth 8 ../rata-body\;32x32\,16\,30.png

montage -geometry +0+0 -background none \
head-stand-23.png \
head-stand-45.png \
head-stand-68.png \
head-stand-90.png \
head-stand-135.png \
head-stand-158.png \
head-walk-23.png \
head-walk-45.png \
head-walk-68.png \
head-walk-90.png \
head-walk-135.png \
head-walk-158.png \
head-hurtbk.png \
head-hurtfd.png \
head-laybk.png \
head-layfd.png \
-depth 8 ../rata-head\;32x32\,16\,14.png


montage -geometry +0+0 -background none \
dress-body-stand.png \
dress-body-walk.png \
dress-body-tiptoe.png \
dress-body-kneel.png \
dress-body-crawl.png \
dress-body-crawl2.png \
dress-body-sit.png \
dress-body-hurtbk.png \
dress-body-laybk.png \
dress-body-hurtfd.png \
dress-body-layfd.png \
dress-body-grab.png \
-depth 8 ../dress-body\;32x32\,16\,30.png

montage -geometry +0+0 -background none \
dress-arm-0.png \
dress-arm-23.png \
dress-arm-45.png \
dress-arm-68.png \
dress-arm-90.png \
dress-arm-113.png \
dress-arm-135.png \
dress-arm-158.png \
dress-arm-180.png \
-depth 8 ../dress-arm\;32x32\,15\,16.png

montage -geometry +0+0 -background none \
dress-forearm-0.png \
dress-forearm-23.png \
dress-forearm-45.png \
dress-forearm-68.png \
dress-forearm-90.png \
dress-forearm-113.png \
dress-forearm-135.png \
dress-forearm-158.png \
dress-forearm-180.png \
-depth 8 ../dress-forearm\;32x32\,15\,19.png



popd
rm -rf img/rata_tmp
