#!/bin/bash

perl gen_img.pl > img.c++
perl gen_snd.pl > snd.c++
perl gen_roomlist.pl > roomlist.c++

LD_RUN_PATH=lib g++ -Wall -Wno-write-strings -Wno-switch -Wno-reorder -Wno-format -ggdb -finline-small-functions lib/libsfml-graphics.so.1.6 lib/libBox2D.so.2.1.0 lib/libsfml-audio.so.1.6 -o test main.c++ && ./test


