#!/bin/bash

perl tools/gen_img.pl > img.c++
perl tools/gen_snd.pl > snd.c++
perl tools/gen_roomlist.pl > roomlist.c++

LD_RUN_PATH=lib g++ -Wall -Wno-write-strings -Wno-switch -Wno-reorder -Wno-format -finline-small-functions -fwhole-program -fno-rtti -fmax-errors=10 -lGL lib/libsfml-system.so.1.6 lib/libsfml-window.so.1.6 lib/libSOIL.so.1 lib/libsfml-audio.so.1.6 lib/libBox2D.so.2.1.0 -o test main.c++ && ./test


