#!/bin/bash

perl tools/gen_img.pl > img.c++
perl tools/gen_snd.pl > snd.c++
perl tools/gen_roomlist.pl > roomlist.c++

LD_RUN_PATH=lib g++ -Wall -Wno-write-strings -Wno-switch -Wno-reorder -Wno-format -fwhole-program -fmax-errors=10 -ggdb main.c++ -lGL -lglfw -lSOIL /usr/lib/libsfml-audio.so.1.6 lib/libBox2D.so.2.1.0 -o test-dbg && gdb ./test-dbg


