#!/bin/bash

LD_RUN_PATH=lib g++ -Wall -Wno-write-strings -Wno-switch -Wno-reorder -Wno-format -O3 -fwhole-program -fno-rtti -lGL lib/libsfml-system.so.1.6 lib/libsfml-window.so.1.6 lib/libSOIL.so.1 lib/libsfml-audio.so.1.6 lib/libBox2D.so.2.1.0 -o test main.c++ && ./test


