#!/bin/bash

LD_RUN_PATH=lib g++ -Wall -Wno-write-strings -Wno-switch -Wno-reorder -Wno-format -O1 -pg -lGL lib/libsfml-system.so.1.6 lib/libsfml-window.so.1.6 lib/libSOIL.so.1 lib/libBox2D.so.2.1.0 lib/libsfml-audio.so.1.6 -o test main.c++ && ./test


